name: generate pacman game
on:
  schedule:
    - cron: '0 */24 * * *' # Runs automatically every 24 hours
  workflow_dispatch:      # Allows you to run it manually anytime
  push:
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Pacman SVG
        uses: DuyetBKU/viz-pacman-github-profile@main
        with:
          username: ${{ github.repository_owner }}
          output: pacman.svg
          theme: react-dark
